import type { CatalogEntryWithCategory } from './furnitureCatalog.js'
import {
  LARGE_SCREEN_A_SPRITE,
  LARGE_SCREEN_B_SPRITE,
  PC_TOWER_A_ON_SPRITE,
  PC_TOWER_A_OFF_SPRITE,
  PC_TOWER_B_ON_SPRITE,
  PC_TOWER_B_OFF_SPRITE,
  LAPTOP_CLOSED_SPRITE,
  LAPTOP_OPEN_FRONT_SPRITE,
  LAPTOP_OPEN_BACK_SPRITE,
  LAPTOP_OPEN_LEFT_SPRITE,
  LAPTOP_OPEN_RIGHT_SPRITE,
  LAPTOP_OPEN_TOP_SPRITE,
  PHONE_SPRITE,
  PRINTER_B_SPRITE,
} from '../sprites/spriteData-electronics.js'

export const ELECTRONICS_CATALOG_ENTRIES: CatalogEntryWithCategory[] = [
  // ── Large screens ──────────────────────────────────────────────
  {
    type: 'large_screen_a',
    label: 'Large Monitor',
    footprintW: 2,
    footprintH: 2,
    sprite: LARGE_SCREEN_A_SPRITE,
    isDesk: false,
    category: 'electronics',
  },
  {
    type: 'large_screen_b',
    label: 'Wide Monitor',
    footprintW: 2,
    footprintH: 1,
    sprite: LARGE_SCREEN_B_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },

  // ── PC Tower A — on/off toggle pair ───────────────────────────
  {
    type: 'pc_tower_a_off',
    label: 'PC Tower',
    footprintW: 1,
    footprintH: 1,
    sprite: PC_TOWER_A_OFF_SPRITE,
    isDesk: false,
    category: 'electronics',
    groupId: 'pc_tower_a',
    orientation: 'front',
    state: 'off',
  },
  {
    type: 'pc_tower_a_on',
    label: 'PC Tower (on)',
    footprintW: 1,
    footprintH: 1,
    sprite: PC_TOWER_A_ON_SPRITE,
    isDesk: false,
    category: 'electronics',
    groupId: 'pc_tower_a',
    orientation: 'front',
    state: 'on',
  },

  // ── PC Tower B — on/off toggle pair ───────────────────────────
  {
    type: 'pc_tower_b_off',
    label: 'PC Tower B',
    footprintW: 1,
    footprintH: 1,
    sprite: PC_TOWER_B_OFF_SPRITE,
    isDesk: false,
    category: 'electronics',
    groupId: 'pc_tower_b',
    orientation: 'front',
    state: 'off',
  },
  {
    type: 'pc_tower_b_on',
    label: 'PC Tower B (on)',
    footprintW: 1,
    footprintH: 1,
    sprite: PC_TOWER_B_ON_SPRITE,
    isDesk: false,
    category: 'electronics',
    groupId: 'pc_tower_b',
    orientation: 'front',
    state: 'on',
  },

  // ── Laptop variants ────────────────────────────────────────────
  {
    type: 'laptop_closed',
    label: 'Laptop (closed)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_CLOSED_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'laptop_open_front',
    label: 'Laptop (open)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_OPEN_FRONT_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'laptop_open_back',
    label: 'Laptop (back)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_OPEN_BACK_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'laptop_open_left',
    label: 'Laptop (left)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_OPEN_LEFT_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'laptop_open_right',
    label: 'Laptop (right)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_OPEN_RIGHT_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'laptop_open_top',
    label: 'Laptop (top)',
    footprintW: 1,
    footprintH: 1,
    sprite: LAPTOP_OPEN_TOP_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },

  // ── Desk accessories ───────────────────────────────────────────
  {
    type: 'desk_phone',
    label: 'Desk Phone',
    footprintW: 1,
    footprintH: 1,
    sprite: PHONE_SPRITE,
    isDesk: false,
    category: 'electronics',
    canPlaceOnSurfaces: true,
  },
  {
    type: 'printer_b',
    label: 'Inkjet Printer',
    footprintW: 1,
    footprintH: 1,
    sprite: PRINTER_B_SPRITE,
    isDesk: false,
    category: 'electronics',
  },
]
