import type { CatalogEntryWithCategory } from './furnitureCatalog.js'
import {
  LARGE_WINDOW_A_SPRITE,
  LARGE_WINDOW_B_SPRITE,
  LARGE_WINDOW_C_SPRITE,
  SMALL_WINDOW_A_SPRITE,
  SMALL_WINDOW_B_SPRITE,
  SMALL_WINDOW_C_SPRITE,
} from '../sprites/spriteData-windows.js'

export const WINDOW_CATALOG_ENTRIES: CatalogEntryWithCategory[] = [
  {
    type: 'large_window_a',
    label: 'Window (large)',
    footprintW: 3,
    footprintH: 1,
    sprite: LARGE_WINDOW_A_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
  {
    type: 'large_window_b',
    label: 'Window (arched)',
    footprintW: 3,
    footprintH: 1,
    sprite: LARGE_WINDOW_B_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
  {
    type: 'large_window_c',
    label: 'Window (extra wide)',
    footprintW: 4,
    footprintH: 1,
    sprite: LARGE_WINDOW_C_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
  {
    type: 'small_window_a',
    label: 'Window (small)',
    footprintW: 2,
    footprintH: 1,
    sprite: SMALL_WINDOW_A_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
  {
    type: 'small_window_b',
    label: 'Window (tiny)',
    footprintW: 1,
    footprintH: 1,
    sprite: SMALL_WINDOW_B_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
  {
    type: 'small_window_c',
    label: 'Window (shuttered)',
    footprintW: 2,
    footprintH: 1,
    sprite: SMALL_WINDOW_C_SPRITE,
    isDesk: false,
    category: 'wall',
    canPlaceOnWalls: true,
  },
]
